FROM golang:1.22-bookworm as builder

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --no-install-recommends -y curl wget \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean
